name: Pipeline
on: [push]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Run ESLint
        run: npm run js:lint
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run test:prepare
          headless: true
